volumes:
  data:

networks:
  traefik:
    external: true

services:
  grafana:
    image: grafana/grafana:${VERSION:?}
    container_name: ${NAME:-grafana}
    user: ${RUN_USER:-oci}:${RUN_GROUP:-oci}
    volumes:
      - data:/var/lib/grafana
    networks:
      - traefik
    labels:
      - "traefik.http.routers.${ROUTER:-grafana}.rule=Host(`${DOMAIN:-grafana.local.krislamo.org}`)"
      - "traefik.http.services.${ROUTER:-grafana}.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
